data:
  datasets: ["switchboard", "fisher"]
  type: "sliding"
  sample_rate: 16_000
  audio_duration: 10
  audio_normalize: False
  audio_overlap: 2
  vad_hz: 50
  vad_horizon: 2
  vad_history: False
  vad_history_times: [60, 30, 10, 5]
  flip_channels: true
  flip_probability: 0.5
  mask_vad: true
  mask_vad_probability: 0.5
  batch_size: 16
  num_workers: 24
