dataset:
  datasets: ["switchboard"]
  type: "sliding"
  sample_rate: 16000
  audio_mono: true
  audio_duration: 10
  audio_normalize: true
  # Sliding Dataset
  audio_overlap: 2
  # IPU Dataset
  audio_context_duration: 5 # minimum context before ipu-end to count
  ipu_min_time: 1 # ipus must be longer than this to count
  ipu_pause_time: 0.2 # pause length must be longer than this to count
  # VAD
  vad_hz: 100
  vad_bin_times: [.2, .4, .6, .8]
  vad_threshold_ratio: 0.5
  vad_history: true
  vad_history_times: [60, 30, 10, 5]
